// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlporswkkghmvpmzsnwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhscG9yc3dra2dobXZwbXpzbndhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Nzc4ODgsImV4cCI6MjA2NjU1Mzg4OH0.RM_MwPuTVPD_DJa7Qy_dTiHIYX_xCb8djQFHty8yNsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);